import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import crypto from 'node:crypto';
const source=fs.readFileSync(new URL('../google/Code.gs',import.meta.url),'utf8');
function server(){const sheets=new Map(),props=new Map(),book={getId:()=> 'test-sheet',getSheetByName:n=>sheets.get(n),insertSheet:n=>{const rows=[];const s={rows,getLastRow:()=>rows.length,setFrozenRows(){},getRange(row,col,height,width){return {getValues:()=>Array.from({length:height},(_,i)=>Array.from({length:width},(_,j)=>rows[row-1+i]?.[col-1+j]??'')),setValues(values){values.forEach((r,i)=>{rows[row-1+i]??=[];r.forEach((v,j)=>rows[row-1+i][col-1+j]=v)});return this},setFontWeight(){return this},setBackground(){return this}}}};sheets.set(n,s);return s}};
const ui={ButtonSet:{OK_CANCEL:1},Button:{OK:1},prompt:()=>({getSelectedButton:()=>1,getResponseText:()=> 'test-only-passphrase'}),alert(){}};
const context=vm.createContext({console,SpreadsheetApp:{getActiveSpreadsheet:()=>book,openById:()=>book,getUi:()=>ui,flush(){}},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k),setProperty:(k,v)=>props.set(k,v)})},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_,s)=>[...crypto.createHash('sha256').update(s).digest()]},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})}});
vm.runInContext(source,context);context.setupEnglish();return {call:r=>JSON.parse(JSON.stringify(context.englishApi({app:'english-practice',pin:'test-only-passphrase',action:'sync',since:0,events:[],collections:[],...r}))),sheets};}
const event={id:'answer-1',type:'attempt',at:'2026-09-25T17:00:00.000Z',data:{lessonId:'start-01',taskId:'intro',answer:'=This is literal text',task:{prompt:'Say hello'}}};
test('append is idempotent, text stays literal, readback preserves original answer',()=>{const s=server();let r=s.call({events:[event]});assert.equal(r.cursor,1);assert.equal(r.events[0].data.answer,event.data.answer);r=s.call({events:[event]});assert.equal(r.events.length,1);assert.equal(s.sheets.get('Eingaben').rows.length,2);assert.deepEqual(r.accepted,['answer-1']);});
test('wrong PIN and changed duplicate ID do not overwrite stored responses',()=>{const s=server();assert.throws(()=>s.call({pin:'bad'}),/Zugangscode/);s.call({events:[event]});assert.throws(()=>s.call({events:[{...event,data:{...event.data,answer:'other'}}]}),/Doppelte/);assert.equal(s.call({}).events[0].data.answer,event.data.answer)});
test('collection revisions retain both versions on conflicts and acknowledge retries',()=>{const s=server(),op={id:'c1',opId:'op1',baseRevision:0,value:{id:'c1',name:'C',words:[]}};let r=s.call({collections:[op]});assert.equal(r.collectionAccepted[0].revision,1);r=s.call({collections:[op]});assert.equal(r.collectionAccepted[0].revision,1);r=s.call({collections:[{...op,opId:'op2'}]});assert.equal(r.conflicts[0].revision,1);assert.equal(s.sheets.get('Sammlungen').rows.length,2)});
test('client cannot alter teacher content or publish arbitrary event types',()=>{const s=server();assert.throws(()=>s.call({events:[{...event,type:'feedback'}]}),/Ungültiger/);assert.throws(()=>s.call({since:10}),/älter/)});
test('pagination recovers all entries without duplicates',()=>{const s=server();for(let j=0;j<6;j++)s.call({events:Array.from({length:100},(_,i)=>({...event,id:'e-'+(j*100+i)}))});const one=s.call({since:0}),two=s.call({since:one.cursor});assert.equal(one.events.length,500);assert.equal(one.more,true);assert.equal(two.events.length,100);assert.equal(two.more,false);assert.equal(two.cursor,600)});
